version: "3"

services:
    my-new-services:
        container_name: my-services
        ports:
            - "3000:3000"
        build: .
        privileged: true
        restart: unless-stopped
        networks:
            - my-network
    # my-services:
    #     container_name: my-services
    #     network_mode: "host"
    #     expose:
    #     - "3000"
    #     privileged: true
    #     restart: unless-stopped

networks:
    my-network:
        # Use a custom driver which takes special options
        driver: bridge
